//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 03:27:43 PM PDT 
//


package org.dsa.iot.knx.masterdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AddressSpace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StartAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PtrResource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InterfaceObjectRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PropertyID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Occurrence" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Location")
public class Location {

    @XmlAttribute(name = "AddressSpace")
    protected String addressSpace;
    @XmlAttribute(name = "StartAddress")
    protected String startAddress;
    @XmlAttribute(name = "PtrResource")
    protected String ptrResource;
    @XmlAttribute(name = "InterfaceObjectRef")
    protected String interfaceObjectRef;
    @XmlAttribute(name = "PropertyID")
    protected String propertyID;
    @XmlAttribute(name = "Occurrence")
    protected String occurrence;

    /**
     * Gets the value of the addressSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressSpace() {
        return addressSpace;
    }

    /**
     * Sets the value of the addressSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressSpace(String value) {
        this.addressSpace = value;
    }

    /**
     * Gets the value of the startAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAddress() {
        return startAddress;
    }

    /**
     * Sets the value of the startAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAddress(String value) {
        this.startAddress = value;
    }

    /**
     * Gets the value of the ptrResource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtrResource() {
        return ptrResource;
    }

    /**
     * Sets the value of the ptrResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtrResource(String value) {
        this.ptrResource = value;
    }

    /**
     * Gets the value of the interfaceObjectRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceObjectRef() {
        return interfaceObjectRef;
    }

    /**
     * Sets the value of the interfaceObjectRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceObjectRef(String value) {
        this.interfaceObjectRef = value;
    }

    /**
     * Gets the value of the propertyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyID() {
        return propertyID;
    }

    /**
     * Sets the value of the propertyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyID(String value) {
        this.propertyID = value;
    }

    /**
     * Gets the value of the occurrence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccurrence() {
        return occurrence;
    }

    /**
     * Sets the value of the occurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccurrence(String value) {
        this.occurrence = value;
    }

}
