//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 03:27:43 PM PDT 
//


package org.dsa.iot.knx.masterdata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.knx.xml.project._13 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.knx.xml.project._13
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link KNX }
     * 
     */
    public KNX createKNX() {
        return new KNX();
    }

    /**
     * Create an instance of {@link KNX.MasterData }
     * 
     */
    public KNX.MasterData createKNXMasterData() {
        return new KNX.MasterData();
    }

    /**
     * Create an instance of {@link KNX.MasterData.Manufacturers }
     * 
     */
    public KNX.MasterData.Manufacturers createKNXMasterDataManufacturers() {
        return new KNX.MasterData.Manufacturers();
    }

    /**
     * Create an instance of {@link KNX.MasterData.Manufacturers.Manufacturer }
     * 
     */
    public KNX.MasterData.Manufacturers.Manufacturer createKNXMasterDataManufacturersManufacturer() {
        return new KNX.MasterData.Manufacturers.Manufacturer();
    }

    /**
     * Create an instance of {@link KNX.MasterData.Manufacturers.Manufacturer.PublicKeys }
     * 
     */
    public KNX.MasterData.Manufacturers.Manufacturer.PublicKeys createKNXMasterDataManufacturersManufacturerPublicKeys() {
        return new KNX.MasterData.Manufacturers.Manufacturer.PublicKeys();
    }

    /**
     * Create an instance of {@link KNX.MasterData.Manufacturers.Manufacturer.PublicKeys.PublicKey }
     * 
     */
    public KNX.MasterData.Manufacturers.Manufacturer.PublicKeys.PublicKey createKNXMasterDataManufacturersManufacturerPublicKeysPublicKey() {
        return new KNX.MasterData.Manufacturers.Manufacturer.PublicKeys.PublicKey();
    }

    /**
     * Create an instance of {@link KNX.MasterData.FunctionalBlocks }
     * 
     */
    public KNX.MasterData.FunctionalBlocks createKNXMasterDataFunctionalBlocks() {
        return new KNX.MasterData.FunctionalBlocks();
    }

    /**
     * Create an instance of {@link KNX.MasterData.FunctionalBlocks.FunctionalBlock }
     * 
     */
    public KNX.MasterData.FunctionalBlocks.FunctionalBlock createKNXMasterDataFunctionalBlocksFunctionalBlock() {
        return new KNX.MasterData.FunctionalBlocks.FunctionalBlock();
    }

    /**
     * Create an instance of {@link KNX.MasterData.FunctionalBlocks.FunctionalBlock.Parameters }
     * 
     */
    public KNX.MasterData.FunctionalBlocks.FunctionalBlock.Parameters createKNXMasterDataFunctionalBlocksFunctionalBlockParameters() {
        return new KNX.MasterData.FunctionalBlocks.FunctionalBlock.Parameters();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions }
     * 
     */
    public KNX.MasterData.MaskVersions createKNXMasterDataMaskVersions() {
        return new KNX.MasterData.MaskVersions();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion createKNXMasterDataMaskVersionsMaskVersion() {
        return new KNX.MasterData.MaskVersions.MaskVersion();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationData() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataInterfaceObjects() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects.InterfaceObject }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects.InterfaceObject createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataInterfaceObjectsInterfaceObject() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects.InterfaceObject();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.MemorySegments }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.MemorySegments createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataMemorySegments() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.MemorySegments();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProcedures() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedure() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataResources() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataResourcesResource() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Features }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Features createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataFeatures() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Features();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.MaskEntries }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.MaskEntries createKNXMasterDataMaskVersionsMaskVersionMaskEntries() {
        return new KNX.MasterData.MaskVersions.MaskVersion.MaskEntries();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.DownwardCompatibleMasks }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.DownwardCompatibleMasks createKNXMasterDataMaskVersionsMaskVersionDownwardCompatibleMasks() {
        return new KNX.MasterData.MaskVersions.MaskVersion.DownwardCompatibleMasks();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MediumTypes }
     * 
     */
    public KNX.MasterData.MediumTypes createKNXMasterDataMediumTypes() {
        return new KNX.MasterData.MediumTypes();
    }

    /**
     * Create an instance of {@link KNX.MasterData.PropertyDataTypes }
     * 
     */
    public KNX.MasterData.PropertyDataTypes createKNXMasterDataPropertyDataTypes() {
        return new KNX.MasterData.PropertyDataTypes();
    }

    /**
     * Create an instance of {@link KNX.MasterData.InterfaceObjectProperties }
     * 
     */
    public KNX.MasterData.InterfaceObjectProperties createKNXMasterDataInterfaceObjectProperties() {
        return new KNX.MasterData.InterfaceObjectProperties();
    }

    /**
     * Create an instance of {@link KNX.MasterData.InterfaceObjectTypes }
     * 
     */
    public KNX.MasterData.InterfaceObjectTypes createKNXMasterDataInterfaceObjectTypes() {
        return new KNX.MasterData.InterfaceObjectTypes();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes }
     * 
     */
    public KNX.MasterData.DatapointTypes createKNXMasterDataDatapointTypes() {
        return new KNX.MasterData.DatapointTypes();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType createKNXMasterDataDatapointTypesDatapointType() {
        return new KNX.MasterData.DatapointTypes.DatapointType();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypes() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtype() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormat() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Enumeration }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Enumeration createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatEnumeration() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Enumeration();
    }

    /**
     * Create an instance of {@link Language.TranslationUnit }
     * 
     */
    public Language.TranslationUnit createLanguageTranslationUnit() {
        return new Language.TranslationUnit();
    }

    /**
     * Create an instance of {@link Language.TranslationUnit.TranslationElement }
     * 
     */
    public Language.TranslationUnit.TranslationElement createLanguageTranslationUnitTranslationElement() {
        return new Language.TranslationUnit.TranslationElement();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link AccessRights }
     * 
     */
    public AccessRights createAccessRights() {
        return new AccessRights();
    }

    /**
     * Create an instance of {@link KNX.MasterData.ProductLanguages }
     * 
     */
    public KNX.MasterData.ProductLanguages createKNXMasterDataProductLanguages() {
        return new KNX.MasterData.ProductLanguages();
    }

    /**
     * Create an instance of {@link KNX.MasterData.Languages }
     * 
     */
    public KNX.MasterData.Languages createKNXMasterDataLanguages() {
        return new KNX.MasterData.Languages();
    }

    /**
     * Create an instance of {@link KNX.MasterData.Manufacturers.Manufacturer.PublicKeys.PublicKey.RSAKeyValue }
     * 
     */
    public KNX.MasterData.Manufacturers.Manufacturer.PublicKeys.PublicKey.RSAKeyValue createKNXMasterDataManufacturersManufacturerPublicKeysPublicKeyRSAKeyValue() {
        return new KNX.MasterData.Manufacturers.Manufacturer.PublicKeys.PublicKey.RSAKeyValue();
    }

    /**
     * Create an instance of {@link KNX.MasterData.FunctionalBlocks.FunctionalBlock.Parameters.Parameter }
     * 
     */
    public KNX.MasterData.FunctionalBlocks.FunctionalBlock.Parameters.Parameter createKNXMasterDataFunctionalBlocksFunctionalBlockParametersParameter() {
        return new KNX.MasterData.FunctionalBlocks.FunctionalBlock.Parameters.Parameter();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects.InterfaceObject.Property }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects.InterfaceObject.Property createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataInterfaceObjectsInterfaceObjectProperty() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.InterfaceObjects.InterfaceObject.Property();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.MemorySegments.MemorySegment }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.MemorySegments.MemorySegment createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataMemorySegmentsMemorySegment() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.MemorySegments.MemorySegment();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlSetControlVariable }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlSetControlVariable createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlSetControlVariable() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlSetControlVariable();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteMem }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteMem createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlWriteMem() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteMem();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadImageMem }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadImageMem createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlLoadImageMem() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadImageMem();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlUnload }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlUnload createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlUnload() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlUnload();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoad }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoad createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlLoad() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoad();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlAbsSegment }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlAbsSegment createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlAbsSegment() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlAbsSegment();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskSegment }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskSegment createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlTaskSegment() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskSegment();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskPtr }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskPtr createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlTaskPtr() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskPtr();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskCtrl1 }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskCtrl1 createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlTaskCtrl1() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskCtrl1();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskCtrl2 }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskCtrl2 createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlTaskCtrl2() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlTaskCtrl2();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadCompleted }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadCompleted createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlLoadCompleted() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadCompleted();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlDelay }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlDelay createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlDelay() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlDelay();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlCompareMem }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlCompareMem createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlCompareMem() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlCompareMem();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMerge }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMerge createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlMerge() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMerge();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMapError }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMapError createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlMapError() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMapError();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlRelSegment }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlRelSegment createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlRelSegment() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlRelSegment();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteRelMem }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteRelMem createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlWriteRelMem() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteRelMem();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteProp }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteProp createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlWriteProp() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlWriteProp();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadImageProp }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadImageProp createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlLoadImageProp() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlLoadImageProp();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlCompareProp }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlCompareProp createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlCompareProp() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlCompareProp();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlClearLCFilterTable }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlClearLCFilterTable createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlClearLCFilterTable() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlClearLCFilterTable();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMasterReset }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMasterReset createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataProceduresProcedureLdCtrlMasterReset() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Procedures.Procedure.LdCtrlMasterReset();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource.ImgLocation }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource.ImgLocation createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataResourcesResourceImgLocation() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource.ImgLocation();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource.ResourceType }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource.ResourceType createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataResourcesResourceResourceType() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Resources.Resource.ResourceType();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Features.Feature }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Features.Feature createKNXMasterDataMaskVersionsMaskVersionHawkConfigurationDataFeaturesFeature() {
        return new KNX.MasterData.MaskVersions.MaskVersion.HawkConfigurationData.Features.Feature();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.MaskEntries.MaskEntry }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.MaskEntries.MaskEntry createKNXMasterDataMaskVersionsMaskVersionMaskEntriesMaskEntry() {
        return new KNX.MasterData.MaskVersions.MaskVersion.MaskEntries.MaskEntry();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MaskVersions.MaskVersion.DownwardCompatibleMasks.DownwardCompatibleMask }
     * 
     */
    public KNX.MasterData.MaskVersions.MaskVersion.DownwardCompatibleMasks.DownwardCompatibleMask createKNXMasterDataMaskVersionsMaskVersionDownwardCompatibleMasksDownwardCompatibleMask() {
        return new KNX.MasterData.MaskVersions.MaskVersion.DownwardCompatibleMasks.DownwardCompatibleMask();
    }

    /**
     * Create an instance of {@link KNX.MasterData.MediumTypes.MediumType }
     * 
     */
    public KNX.MasterData.MediumTypes.MediumType createKNXMasterDataMediumTypesMediumType() {
        return new KNX.MasterData.MediumTypes.MediumType();
    }

    /**
     * Create an instance of {@link KNX.MasterData.PropertyDataTypes.PropertyDataType }
     * 
     */
    public KNX.MasterData.PropertyDataTypes.PropertyDataType createKNXMasterDataPropertyDataTypesPropertyDataType() {
        return new KNX.MasterData.PropertyDataTypes.PropertyDataType();
    }

    /**
     * Create an instance of {@link KNX.MasterData.InterfaceObjectProperties.InterfaceObjectProperty }
     * 
     */
    public KNX.MasterData.InterfaceObjectProperties.InterfaceObjectProperty createKNXMasterDataInterfaceObjectPropertiesInterfaceObjectProperty() {
        return new KNX.MasterData.InterfaceObjectProperties.InterfaceObjectProperty();
    }

    /**
     * Create an instance of {@link KNX.MasterData.InterfaceObjectTypes.InterfaceObjectType }
     * 
     */
    public KNX.MasterData.InterfaceObjectTypes.InterfaceObjectType createKNXMasterDataInterfaceObjectTypesInterfaceObjectType() {
        return new KNX.MasterData.InterfaceObjectTypes.InterfaceObjectType();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Float }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Float createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatFloat() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Float();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.SignedInteger }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.SignedInteger createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatSignedInteger() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.SignedInteger();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.String }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.String createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatString() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.String();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Bit }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Bit createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatBit() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Bit();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.UnsignedInteger }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.UnsignedInteger createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatUnsignedInteger() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.UnsignedInteger();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Reserved }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Reserved createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatReserved() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Reserved();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.RefType }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.RefType createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatRefType() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.RefType();
    }

    /**
     * Create an instance of {@link KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Enumeration.EnumValue }
     * 
     */
    public KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Enumeration.EnumValue createKNXMasterDataDatapointTypesDatapointTypeDatapointSubtypesDatapointSubtypeFormatEnumerationEnumValue() {
        return new KNX.MasterData.DatapointTypes.DatapointType.DatapointSubtypes.DatapointSubtype.Format.Enumeration.EnumValue();
    }

    /**
     * Create an instance of {@link Language.TranslationUnit.TranslationElement.Translation }
     * 
     */
    public Language.TranslationUnit.TranslationElement.Translation createLanguageTranslationUnitTranslationElementTranslation() {
        return new Language.TranslationUnit.TranslationElement.Translation();
    }

}
