//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 12:26:56 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://knx.org/xml/project/12", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.dsa.iot.knx.masterdata;
