//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.18 at 03:48:38 PM PST 
//


package org.dsa.iot.knx.groupaddress;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.knx.xml.ga_export._01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.knx.xml.ga_export._01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GroupRange }
     * 
     */
    public GroupRange createGroupRange() {
        return new GroupRange();
    }

    /**
     * Create an instance of {@link GroupRange.GroupAddress }
     * 
     */
    public GroupRange.GroupAddress createGroupRangeGroupAddress() {
        return new GroupRange.GroupAddress();
    }

    /**
     * Create an instance of {@link GroupAddressExport }
     * 
     */
    public GroupAddressExport createGroupAddressExport() {
        return new GroupAddressExport();
    }

}
