//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.18 at 03:48:38 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://knx.org/xml/ga-export/01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.dsa.iot.knx.groupaddress;
