//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.22 at 01:36:37 PM PDT 
//


package org.dsa.iot.knx.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://knx.org/xml/project/13}BinaryData"/>
 *         &lt;element ref="{http://knx.org/xml/project/13}GroupAddress"/>
 *         &lt;element ref="{http://knx.org/xml/project/13}BuildingPart"/>
 *         &lt;element ref="{http://knx.org/xml/project/13}GroupRange"/>
 *         &lt;element ref="{http://knx.org/xml/project/13}Trade"/>
 *         &lt;element ref="{http://knx.org/xml/project/13}KNX"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "binaryDataOrGroupAddressOrBuildingPart"
})
@XmlRootElement(name = "NewDataSet")
public class NewDataSet {

    @XmlElements({
        @XmlElement(name = "BinaryData", type = BinaryData.class),
        @XmlElement(name = "GroupAddress", type = GroupAddress.class),
        @XmlElement(name = "BuildingPart", type = BuildingPart.class),
        @XmlElement(name = "GroupRange", type = GroupRange.class),
        @XmlElement(name = "Trade", type = Trade.class),
        @XmlElement(name = "KNX", type = KNX.class)
    })
    protected List<Object> binaryDataOrGroupAddressOrBuildingPart;

    /**
     * Gets the value of the binaryDataOrGroupAddressOrBuildingPart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryDataOrGroupAddressOrBuildingPart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryDataOrGroupAddressOrBuildingPart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BinaryData }
     * {@link GroupAddress }
     * {@link BuildingPart }
     * {@link GroupRange }
     * {@link Trade }
     * {@link KNX }
     * 
     * 
     */
    public List<Object> getBinaryDataOrGroupAddressOrBuildingPart() {
        if (binaryDataOrGroupAddressOrBuildingPart == null) {
            binaryDataOrGroupAddressOrBuildingPart = new ArrayList<Object>();
        }
        return this.binaryDataOrGroupAddressOrBuildingPart;
    }

}
