//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 01:20:36 PM PDT 
//


package org.dsa.iot.knx.project;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.knx.xml.project._12 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.knx.xml.project._12
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GroupRange }
     * 
     */
    public GroupRange createGroupRange() {
        return new GroupRange();
    }

    /**
     * Create an instance of {@link KNX }
     * 
     */
    public KNX createKNX() {
        return new KNX();
    }

    /**
     * Create an instance of {@link KNX.Project }
     * 
     */
    public KNX.Project createKNXProject() {
        return new KNX.Project();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations }
     * 
     */
    public KNX.Project.Installations createKNXProjectInstallations() {
        return new KNX.Project.Installations();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation }
     * 
     */
    public KNX.Project.Installations.Installation createKNXProjectInstallationsInstallation() {
        return new KNX.Project.Installations.Installation();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.GroupAddresses }
     * 
     */
    public KNX.Project.Installations.Installation.GroupAddresses createKNXProjectInstallationsInstallationGroupAddresses() {
        return new KNX.Project.Installations.Installation.GroupAddresses();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology }
     * 
     */
    public KNX.Project.Installations.Installation.Topology createKNXProjectInstallationsInstallationTopology() {
        return new KNX.Project.Installations.Installation.Topology();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area createKNXProjectInstallationsInstallationTopologyArea() {
        return new KNX.Project.Installations.Installation.Topology.Area();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area.Line }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area.Line createKNXProjectInstallationsInstallationTopologyAreaLine() {
        return new KNX.Project.Installations.Installation.Topology.Area.Line();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance createKNXProjectInstallationsInstallationTopologyAreaLineDeviceInstance() {
        return new KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs createKNXProjectInstallationsInstallationTopologyAreaLineDeviceInstanceComObjectInstanceRefs() {
        return new KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef createKNXProjectInstallationsInstallationTopologyAreaLineDeviceInstanceComObjectInstanceRefsComObjectInstanceRef() {
        return new KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef.Connectors }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef.Connectors createKNXProjectInstallationsInstallationTopologyAreaLineDeviceInstanceComObjectInstanceRefsComObjectInstanceRefConnectors() {
        return new KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef.Connectors();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ParameterInstanceRefs }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ParameterInstanceRefs createKNXProjectInstallationsInstallationTopologyAreaLineDeviceInstanceParameterInstanceRefs() {
        return new KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ParameterInstanceRefs();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link GroupRange.GroupAddress }
     * 
     */
    public GroupRange.GroupAddress createGroupRangeGroupAddress() {
        return new GroupRange.GroupAddress();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.GroupAddresses.GroupRanges }
     * 
     */
    public KNX.Project.Installations.Installation.GroupAddresses.GroupRanges createKNXProjectInstallationsInstallationGroupAddressesGroupRanges() {
        return new KNX.Project.Installations.Installation.GroupAddresses.GroupRanges();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef.Connectors.Send }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef.Connectors.Send createKNXProjectInstallationsInstallationTopologyAreaLineDeviceInstanceComObjectInstanceRefsComObjectInstanceRefConnectorsSend() {
        return new KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ComObjectInstanceRefs.ComObjectInstanceRef.Connectors.Send();
    }

    /**
     * Create an instance of {@link KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ParameterInstanceRefs.ParameterInstanceRef }
     * 
     */
    public KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ParameterInstanceRefs.ParameterInstanceRef createKNXProjectInstallationsInstallationTopologyAreaLineDeviceInstanceParameterInstanceRefsParameterInstanceRef() {
        return new KNX.Project.Installations.Installation.Topology.Area.Line.DeviceInstance.ParameterInstanceRefs.ParameterInstanceRef();
    }

}
