//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.22 at 01:36:37 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://knx.org/xml/project/13", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.dsa.iot.knx.project;
